# Generated by Django 2.2 on 2020-02-03 00:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='date',
            field=models.DateTimeField(default=datetime.date),
        ),
    ]
