# Generated by Django 2.2 on 2020-02-03 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_vehicle_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
